:Char            U8 char match {
    0x41 => "A"
            "B"
            "C"
            "D"
            "E"
            "F"
            "G"
            "H"
            "I"
            "J"
            "K"
            "L"
            "M"
            "N"
            "O"
            "P"
            "Q"
            "R"
            "S"
            "T"
            "U"
            "V"
            "W"
            "X"
            "Y"
            "Z"
    0x00 => Terminator
}

